### ISSUE TITLE
Add OpenCL Device option

### ISSUE THREAD

**Issue by ghost** [wagesj45/butterflow-ui#2]
**Is your feature request related to a problem? Please describe.**
ButterFlow defaults to my iGPU. My iGPU is slow compared to my discrete GPU.

**Describe the solution you'd like**
I would like an option that allows me to select OpenCL device, like the command-line application.

**Comment by wagesj45** [comment]
@BrimsonBhin It would be super helpful if you can test the [new (1.0.4) release](https://github.com/wagesj45/butterflow-ui/releases/tag/1.0.4). I only have a single device on my machine and can't test the solution with a non-default device. If you notice anything wrong please [file another issue](https://github.com/wagesj45/butterflow-ui/issues/new/choose). If it works, I'd greatly appreciate it if you could let me know by replying to this issue.
