### ISSUE TITLE
Error run ButterFlow

### ISSUE THREAD

**Issue by georgysaumen** [wagesj45/butterflow-ui#7]
Hi,

I have used your software to butterflow my video to 60fps but I got this error:

![Untitled](https://user-images.githubusercontent.com/86090065/135576583-20e25bdc-fbee-452b-a692-ef1ef144a316.png)

![Untitled](https://user-images.githubusercontent.com/86090065/135576758-c5d05025-50a4-4f88-bae4-27311615069a.png)

Can you help me fix ?

Thanks!

**Comment by wagesj45** [comment]
Hey, @phanluchoaofficial20. Looking at everything, you don't need the `Keep Subregions` option selected since you have no subregions defined. My guess is that the renderer is looking for a subregion that doesn't exist. Please let me know if that helps!

**Comment by georgysaumen** [comment]
> Hey, @phanluchoaofficial20. Looking at everything, you don't need the `Keep Subregions` option selected since you have no subregions defined. My guess is that the renderer is looking for a subregion that doesn't exist. Please let me know if that helps!

I still cannot run after disable subregions, I still got that error

**Comment by wagesj45** [comment]
> I still cannot run after disable subregions, I still got that error

The next thing I'd check is your video driver, as NVIDIA drivers have caused some issues with OpenCL in the past, which `butterflow` uses. The other thing I'd check is that the video file you're converting doesn't have any errors in it that could be causing the renderer to give up. If you have access to `ffmpeg` you might try running the following command to create a "clean" version of the movie file which you can try feeding into `butterflow`:

```
ffmpeg -err_detect ignore_err -i "your_movie.mkv" -c copy -map 0 "clean_copy.mkv"
```

**Comment by georgysaumen** [comment]
I have create the clean ver and add again to butterflow ui but I still got
that error!

Vào CN, 3 thg 10, 2021 vào lúc 06:26 Jordan Wages <
***@***.***> đã viết:

**Comment by georgysaumen** [comment]
This is the information of movie using MediaInfo:

General
Complete name                            : cleanemchua18-video.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 3.74 GiB
Duration                                 : 1 h 35 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 5 608 kb/s
Writing application                      : Lavf59.5.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : ***@***.***
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 h 35 min
Bit rate mode                            : Variable
Bit rate                                 : 5 620 kb/s
Maximum bit rate                         : 8 430 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.113
Stream size                              : 3.74 GiB (100%)
Writing library                          : x264 core 148 r2717 0d2410d
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0
/ analyse=0x1:0x111 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 /
mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 /
deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 /
lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 /
bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=2 /
b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 /
weightp=2 / keyint=250 / keyint_min=24 / scenecut=0 / intra_refresh=0 /
rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=5620 / ratetol=1.0 /
qcomp=0.50 / qpmin=6 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 /
vbv_maxrate=8430 / vbv_bufsize=11240 / nal_hrd=vbr / filler=0 /
ip_ratio=1.40 / aq=1:1.00
mdhd_Duration                            : 5731708
Codec configuration box                  : avcC

Vào CN, 3 thg 10, 2021 vào lúc 06:26 Jordan Wages <
***@***.***> đã viết:

**Comment by georgysaumen** [comment]
I use movie I download from NF

**Comment by georgysaumen** [comment]
How can I fix it now ? I have also try to use butterflow by command but I always got error OpenCLL not found, I have use command to check it and I received they have found my NVDIA Card but when using command to change to 60fps they back to error OpenCLL not found

**Comment by wagesj45** [comment]
I'm sorry but I don't think this is an issue with `butterflow-ui`. It seems to be an issue with OpenCL, NVIDIA, python, Windows 11 (which it looks like you're using), or butterflow itself. I wish I could offer more help, but this application is just the front-end that passes data to butterflow. You might have better luck posting to butterflow's github issues or to StackOverflow.

**Comment by georgysaumen** [comment]
Thanks!

Vào Th 3, 5 thg 10, 2021 vào lúc 09:27 Jordan Wages <
***@***.***> đã viết:
